// <auto-generated />
namespace SyncMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class instantiatedacalendarinmembermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(instantiatedacalendarinmembermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201705181942071_instantiated a calendar in member model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
