// <auto-generated />
namespace SyncMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class icollectioningroupcalendar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(icollectioningroupcalendar));
        
        string IMigrationMetadata.Id
        {
            get { return "201706021832434_icollection in groupcalendar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
